using System;
using System.Text;
using System.Collections.Immutable;
using Microsoft.CodeAnalysis;

namespace ProjWizInc.Generators {
    [Generator]
    public class BootstrapperGenerator : IIncrementalGenerator {
        public void Initialize(IncrementalGeneratorInitializationContext context) {
            // High-performance incremental pipeline using named method references to strictly avoid lambdas
            context.RegisterSourceOutput(context.CompilationProvider, ExecuteSourceOutput);
        }

        private void ExecuteSourceOutput(SourceProductionContext context, Compilation compilation) {
            // Resolve target symbols robustly from compilation context
            INamedTypeSymbol catalogSymbol = compilation.GetTypeByMetadataName("ProjWizInc.Engine.Data.Definitions.DefinitionCatalog");
            if (catalogSymbol == null) {
                return;
            }

            INamedTypeSymbol listSymbol = compilation.GetTypeByMetadataName("System.Collections.Generic.List`1");
            if (listSymbol == null) {
                return;
            }

            StringBuilder builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("using System;");
            builder.AppendLine("using System.Collections.Generic;");
            builder.AppendLine("using ProjWizInc.Engine.Data.Definitions;");
            builder.AppendLine("using ProjWizInc.Engine.Simulation.Registries;");
            builder.AppendLine("using ProjWizInc.Engine.Data.ADT;");
            builder.AppendLine();
            builder.AppendLine("namespace ProjWizInc.Engine.Simulation.Core {");
            builder.AppendLine("    internal partial class Bootstrapper {");

            // Phase 1: Generate the "MergeCatalogs" partial method
            builder.AppendLine("        // Statically compiled partial merge - zero reflection");
            builder.AppendLine("        private static void MergeCatalogs(DefinitionCatalog master, DefinitionCatalog partial) {");
            builder.AppendLine("            if (partial == null || master == null) {");
            builder.AppendLine("                return;");
            builder.AppendLine("            }");
            builder.AppendLine();

            ImmutableArray<ISymbol> members = catalogSymbol.GetMembers();
            for (int i = 0; i < members.Length; i++) {
                ISymbol member = members[i];

                if (member is IPropertySymbol) {
                    IPropertySymbol property = (IPropertySymbol)member;
                    ITypeSymbol propertyType = property.Type;

                    if (propertyType is INamedTypeSymbol) {
                        INamedTypeSymbol namedType = (INamedTypeSymbol)propertyType;

                        // Robust generic List check bypassing string-based ConstructedFrom calls
                        if (namedType.IsGenericType && SymbolEqualityComparer.Default.Equals(namedType.ConstructedFrom, listSymbol)) {
                            ITypeSymbol itemType = namedType.TypeArguments[0];
                            string propertyName = property.Name;

                            // Safe fully-qualified type string (includes global:: prefix)
                            string itemTypeName = itemType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                            // Generate the explicit list-merging loop
                            builder.Append("            if (partial.");
                            builder.Append(propertyName);
                            builder.Append(" != null) {\n");

                            builder.Append("                if (master.");
                            builder.Append(propertyName);
                            builder.Append(" == null) {\n");

                            builder.Append("                    master.");
                            builder.Append(propertyName);
                            builder.Append(" = new List<");
                            builder.Append(itemTypeName);
                            builder.Append(">();\n");

                            builder.Append("                }\n");

                            builder.Append("                for (int itemIndex = 0; itemIndex < partial.");
                            builder.Append(propertyName);
                            builder.Append(".Count; itemIndex++) {\n");

                            builder.Append("                    master.");
                            builder.Append(propertyName);
                            builder.Append(".Add(partial.");
                            builder.Append(propertyName);
                            builder.Append("[itemIndex]);\n");

                            builder.Append("                }\n");
                            builder.Append("            }\n\n");
                        }
                    }
                }
            }

            builder.AppendLine("        }");
            builder.AppendLine();

            // Phase 2: Generate the "AutoRegisterAllMaps" partial method
            builder.AppendLine("        // Statically compiled partial registration - zero reflection");
            builder.AppendLine("        private static void AutoRegisterAllMaps(DefinitionCatalog catalog, DefinitionRegistry registry) {");

            for (int i = 0; i < members.Length; i++) {
                ISymbol member = members[i];

                if (member is IPropertySymbol) {
                    IPropertySymbol property = (IPropertySymbol)member;
                    ITypeSymbol propertyType = property.Type;

                    if (propertyType is INamedTypeSymbol) {
                        INamedTypeSymbol namedType = (INamedTypeSymbol)propertyType;

                        if (namedType.IsGenericType && SymbolEqualityComparer.Default.Equals(namedType.ConstructedFrom, listSymbol)) {
                            ITypeSymbol itemType = namedType.TypeArguments[0];
                            string propertyName = property.Name;
                            string itemTypeName = itemType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                            // Generate the strongly-typed registration line with fully qualified item type
                            builder.Append("            BuildAndRegisterMap<");
                            builder.Append(itemTypeName);
                            builder.Append(">(catalog.");
                            builder.Append(propertyName);
                            builder.Append(", registry);\n");
                        }
                    }
                }
            }

            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine("}");

            // Register the compiled string buffer into the compilation assembly as a virtual C# file
            context.AddSource("Bootstrapper.g.cs", builder.ToString());
        }
    }
}